apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: ""
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - 'calendar.sayjeyhi.com'
      secretName: calendar-app-tls-v2
  rules:
    - host: 'calendar.sayjeyhi.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calendar-app-service
                port:
                  number: 3000

